ajax_upload/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('ajax_upload.views',
    url(r'^$', 'upload', name='ajax-upload'),
)

oyf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^blog/comments/', include('fluent_comments.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^$', RedirectView.as_view(url= '/ui/'), name='ui home'),
    url(r'^ajax-upload/', include('ajax_upload.urls')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/logout.html'}),
    url(r'^accounts/', include('registration_email.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # FIXME ICOTOI: Redirectionez dupa login catre projects mai degraba decat catre profilul utilizator
    url(r'^accounts/profile/$', RedirectView.as_view (url= '/')),
    url(r'^users/(?P<user>.*)/$', RedirectView.as_view (url= '/')),  # TODO icotoi redirect to profile fill in
    url(r'^ui/', include('ui.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^messages/', include('postman.urls'))
)

ui/urls.py
from django.conf.urls import patterns, url
from ui import views
from django.views.generic import RedirectView

urlpatterns = patterns('',
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^events$', views.events, name='events'),
    url(r'^shuffle$', views.shuffle, name='shuffle'),
    url(r'^addpost$', views.addpost, name='addpost'),
    url(r'^addevent$', views.addevent, name='addevent'),
    url(r'^post/(?P<postId>\d+)', views.post, name="viewpost"),
    #url(r'^project/(?P<projectId>\d+)/$', views.project, name='project'),
    #url(r'^addproject$', views.addproject, name='addproject'),
    #url(r'^project/(?P<projectId>\d+)/edit$', views.editproject, name='editproject'),
    #url(r'^project/(?P<projectId>\d+)/sensor/(?P<sensorId>\d+)/$', views.sensor, name='sensor'),
    #url(r'^project/(?P<projectId>\d+)/addsensor$', views.addsensor, name='addsensor'),
    #url(r'^project/(?P<projectId>\d+)/sensor/(?P<sensorId>\d+)/edit$', views.editsensor, name='editsensor'),
    #url(r'^profile/(?P<userName>[a-zA-Z0-9_.-]+)$', views.profile, name='profile'),
    #url(r'^profile/(?P<userName>[a-zA-Z0-9_.-]+)/edit$', views.editprofile, name='editprofile'),
    #url(r'^about$', views.about, name='about'),
    #url(r'^contact$', views.contact.as_view(), name='contact'),
    #url(r'^thankyou$', direct_to_template, {'template': 'frontend/thankyou.html'}, name='thankyou')
)

api/models.py
from django.db import models
from django.contrib.auth.models import User 
#from django.contrib.gis.db import models
from taggit.managers import TaggableManager
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, SmartResize, ResizeToFit

# Create your models here.
#class dataType(models.Model):
#    name = models.CharField(max_length = 25, default="Integer")
#    storedType = models.CharField(max_length = 25, default="IntegerField")

class Post(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length = 25)
    description = models.TextField(max_length = 250, default="", blank=True)
#    accessToken = models.CharField(max_length = 40, default="")
#    public = models.NullBooleanField(default=False, null=True)
    picture = models.FileField(upload_to='user/posts/%Y/%m/%d', 
                               default="", 
                               help_text="max. 5MB", 
                               verbose_name="Select an image file", 
                               blank=False)
    picture_home = ImageSpecField(source='picture',
                                      processors=[ResizeToFit(368, 600)],
                                      format='JPEG',
                                      options={'quality': 60})
    tags = TaggableManager()
    timestamp = models.DateTimeField(auto_now_add = True)
#    location = models.PointField(null=True)
#    objects  = models.GeoManager()
# Create your models here.

ui/models.py
from django.db import models

# Create your models here.

ui/forms.py
from api.models import Post
from django import forms
from ajax_upload.widgets import AjaxClearableFileInput

class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        widgets = {
            'name'        : forms.TextInput(attrs={'placeholder': 'Title'}),
            'picture'     : AjaxClearableFileInput,
            'tags'        : forms.TextInput(attrs={'placeholder': 'Tags'}),
#            'description' : forms.Textarea(attrs={'placeholder': 'Description'})
        }
        exclude = ('user', 'description', 'picture_home') # These are filled in the view

    # def clean_name(self):
    #     super(AddProjectForm, self).clean()
    #     cleaned_data = self.cleaned_data
    #     nameField = cleaned_data.get('name', None)
    #     if ' ' in nameField:
    #         raise forms.ValidationError(u'Project Name cannot contain spaces')
    #         return nameField
    #     else:
    #         return nameField

ui/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.shortcuts import render_to_response, render, get_object_or_404
from django.template.context import RequestContext
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserChangeForm
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
import uuid
from forms import AddPostForm
from api.models import Post


# Home page
def dashboard(request):
    return render(request, 'ui/home.html', {
        'page_title': "OFFYOURFACE | Home",
        })


def events(request):
    return render_to_response('ui/events.html', RequestContext(request))


def shuffle(request):
    return render_to_response('ui/shuffle.html', RequestContext(request))


def addpost(request):
    if request.method == 'POST' and request.user is not None: # If the form has been submitted...
        form = AddPostForm(request.POST, request.FILES ) # A form bound to the POST data
        if form.is_valid():
            newPost = form.save(commit = False)
            newPost.accessToken = str(uuid.uuid4())
            newPost.user = request.user
            newPost.save()
            # Save tags
            form.save_m2m()

            return HttpResponseRedirect('/') # Redirect after POST
    else:
        form = AddPostForm()
    return render(request, 'ui/addpost.html', {
        'form': form,
        })


def addevent(request):
    return render_to_response('ui/addevent.html', RequestContext(request))


def post(request, postId):
    thisPost = get_object_or_404(Post, pk=postId)
    thisPostTags = thisPost.tags.all()
    related = thisPost.tags.similar_objects()
    return render(request, 'ui/post.html', {
        'page_title': "OFFYOURFACE | " + thisPost.name,
        'post': thisPost,
        'tags': thisPostTags,
        'related_posts': related,
        })

templates/ui/addevent.html
{% extends 'base.html' %}
{% block content %}
<div id="container">
  <div class="well">
    <form name="create_project" method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{ form.non_field_errors }}</p>
    <div class="row-fluid">
      <div class="span4">
          {% if form.name.errors %}
            <p class="errors">{{ form.name.errors.as_text }}</p>
          {% endif %}
        {{ form.name }}
      </div>
    </div>
    <div class="row-fluid">
      <div class="span4">
        <p>{{ form.picture.label_tag }} ({{ form.picture.help_text }})</p>
        {% if form.picture.errors %}
            <p class="errors">{{ form.picture.errors.as_text }}</p>
        {% endif %}
        {{ form.picture }}
      </div>
      <script>
        new AjaxUploadWidget($('#id_picture'), {
            // options
        });
      </script>
    </div>
    <div class="row-fluid">
      <div class="span4">
        <p>{{ form.tags.label_tag }} ({{ form.tags.help_text }})</p>
        {% if form.tags.errors %}
            <p class="errors">{{ form.tags.errors.as_text }}</p>
        {% endif %}
        {{ form.tags }}
      </div>
    </div>
    <div class="row-fluid">
      <div class="span4">
        <a href="javascript:void(0);" onClick="javascript:addPost();" class="btn btn-primary btn-small">Add post</a>
      </div>
    </div>
    </form>
  </div>
</div>
  <script>
  function addPost() {
    document.forms[0].submit();
  }
  </script>

  {% endblock %}

templates/ui/addpost.html
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Add new post</h3>
  </div>
  <div class="modal-body">

          <div class="row-fluid">
            <div class="span7">
            <form name="create_post" method="POST" action="" enctype="multipart/form-data" id="add-post-form">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <div class="row-fluid">
              <div class="span4">
                  {% if form.name.errors %}
                    <p class="errors">{{ form.name.errors.as_text }}</p>
                  {% endif %}
                {{ form.name }}
              </div>
            </div>
            <div class="row-fluid">
              <div class="span4">
                {% if form.picture.errors %}
                    <p class="errors">{{ form.picture.errors.as_text }}</p>
                {% endif %}
                {{ form.picture }}
              </div>
              <script>
                new AjaxUploadWidget($('#id_picture'), {
                    // options
                });
              </script>
            </div>
            <div class="row-fluid">
              <div class="span4">
                {% if form.tags.errors %}
                    <p class="errors">{{ form.tags.errors.as_text }}</p>
                {% endif %}
                {{ form.tags }}
              </div>
            </div>
            </form>
        </div>

    </div>
  <script>
      function addPost() {
        //document.forms[0].submit();
        var jqxhr = $.post("/ui/addpost", $("#add-post-form").serialize());
        jqxhr.done(function(){
                console.log("done add post");
                $("#addpost-modal").modal("hide");
                setTimeout(function(){
                    window.location.href = "/";
                        }, 10);
            });
        jqxhr.fail(function(){
                console.log("fail add post");
            });
      }

      $(document).ready(function(){
        $(".btn-change").hide();
        $(".btn-remove").hide();
        $(".ajax-upload").hide();
        $(".ajax-upload-preview-area").click(function(){
            $(".ajax-upload").click();
        });
      });
  </script>

  </div>
  <div class="modal-footer">
    <a href="#" class="btn">Close</a>
    <a href="javascript:void(0);" onClick="javascript:addPost();" class="btn btn-primary btn-small">Add post</a>
  </div>

templates/ui/events.html
{% extends "base.html" %}
{% load i18n %}
{% load thumbnail %}
{% block content %}
  <div id="container">
    <div class="row-fluid">
      <br>
    </div>
    <div id="posts" class="isotope row">
    <!-- Posts will go here ... -->
    </div>

    <script src="http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>
    <script src="{{STATIC_URL}}js/jquery.ba-hashchange.min.js"></script>
    <script src="{{STATIC_URL}}js/jquery.isotope.min.js"></script>
    <script src="{{STATIC_URL}}js/mql.js"></script>
    <script src="{{STATIC_URL}}js/oyf.js"></script>
    <script src="{{STATIC_URL}}js/script.js"></script>

    <script id="post" type="text/x-jquery-tmpl">
      <div id="postid-${id}" class="post item span4">
        <div class="well post-well">
          <div id="circle-menu">
            <!-- first expaning path menu -->                        
              <a class="centerbutton" href="javascript:void(0);" title="Share!">
                <span></span>
              </a>
              <ul class="circles">
                <li><a href="" title="Share this on facebook"><span class="facebook"></span></a></li>
                <li><a href="" title="Share this on twitter"><span class="twitter"></span></a></li>
              </ul>
            <!-- second expaning path menu -->
              <a class="centerbutton2" href="javascript:void(0);" title="Add...">
              <span></span>
              </a>
              <ul class="circles2">
                <li><a href="javascript:void(0);" title="Follow this user"><span class="follow_user"></span></a></li>
                <li><a href="javascript:void(0);" title=""><span class="follow_tag"></span></a></li>
              </ul>
          </div> <!-- div menu -->
          <a href="${permalink}" title="${name}">
            <img src="${home_picture}" title="${name}">
            <!--<div class="info">
              <span class="badge">${score}</span>
            </div>-->
            <div class="post-title">
              <h3><span>${title}</span></h3>
            </div>
          </a>
        </div>
      </div>
    </script>
  </div>
{% endblock %}

templates/ui/home.html
{% extends "base.html" %}
{% load i18n %}
{% load thumbnail %}
{% block content %}
  <div id="container">
    <div class="row-fluid">
      <br>
    </div>
    <div id="posts" class="isotope row">
    <!-- Posts will go here ... -->
    </div>

    <script src="http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>
    <script src="{{STATIC_URL}}js/jquery.ba-hashchange.min.js"></script>
    <script src="{{STATIC_URL}}js/jquery.isotope.min.js"></script>
    <script src="{{STATIC_URL}}js/mql.js"></script>
    <script src="{{STATIC_URL}}js/oyf.js"></script>
    <script src="{{STATIC_URL}}js/script.js"></script>

    <script id="post" type="text/x-jquery-tmpl">
      <div id="postid-${id}" class="post item span4">
        <div class="well post-well">
          <div id="circle-menu">
            <!-- first expaning path menu -->                        
              <a class="centerbutton" href="javascript:void(0);" title="Share!">
                <span></span>
              </a>
              <ul class="circles">
                <li><a href="" title="Share this on facebook"><span class="facebook"></span></a></li>
                <li><a href="" title="Share this on twitter"><span class="twitter"></span></a></li>
              </ul>
            <!-- second expaning path menu -->
              <a class="centerbutton2" href="javascript:void(0);" title="Add...">
              <span></span>
              </a>
              <ul class="circles2">
                <li><a href="javascript:void(0);" title="Follow this user"><span class="follow_user"></span></a></li>
                <li><a href="javascript:void(0);" title=""><span class="follow_tag"></span></a></li>
              </ul>
          </div> <!-- div menu -->
          <a href="${permalink}" title="${name}">
            <img src="${home_picture}" title="${name}">
            <!--<div class="info">
              <span class="badge">${score}</span>
            </div>-->
            <div class="post-title">
              <h3><span>${title}</span></h3>
            </div>
          </a>
        </div>
      </div>
    </script>
  </div>
{% endblock %}

templates/ui/post.html
{% extends "base.html" %}
{% load i18n %}
{% load comments %}
{% load url from future %}
{% load thumbnail %}
{% block content %}
  <script type="text/javascript" src="{{ STATIC_URL }}fluent_comments/js/ajaxcomments.js"></script>
  <div id="container">
    <div class="row-fluid">
      <br>
    </div>
    <div class="row-fluid">
      <div class="span10">
        <div class="well post-well">
          <div class="row-fluid">
            <div class="span8">
              <div id="circle-menu">
                <!-- first expaning path menu -->                        
                  <a class="centerbutton" href="javascript:void(0);" title="Share!">
                    <span></span>
                  </a>
                  <ul class="circles">
                    <li><a href="" title="Share this on facebook"><span class="facebook"></span></a></li>
                    <li><a href="" title="Share this on twitter"><span class="twitter"></span></a></li>
                  </ul>
                <!-- second expaning path menu -->
                  <a class="centerbutton2" href="javascript:void(0);" title="Add...">
                  <span></span>
                  </a>
                  <ul class="circles2">
                    <li><a href="javascript:void(0);" title="Follow this user"><span class="follow_user"></span></a></li>
                    <li><a href="javascript:void(0);" title=""><span class="follow_tag"></span></a></li>
                  </ul>
              </div> <!-- div menu -->
              <img src="/media/{{ post.picture }}">
            </div>
            <div class="span4">
              <div class="row-fluid">
                <h3>{{ post.name }}</h3>
              </div>
              <div class="row-fluid">
                <span class="by-user">By <a href="{% url 'dashboard' %}?filter=user&user={{ post.user }}">{{ post.user }}</a></span>
              </div>
              <hr>
              <div class="row-fluid related-content">
                <div class="title-related-content">
                  <h4>Related content</h4>
                </div>
                <ul class="related-posts thumbnails">
                  {% for relatedpost in related_posts %}
                    <li class="related-post span2">
                      {% thumbnail relatedpost.picture "100x100" crop="center" as im %}
                        <a href="{% url 'viewpost' postId=relatedpost.id %}" class="thumbnail">
                          <img src="/media/{{im}}">
                        </a>
                      {% endthumbnail %}
                    </li>
                  {% endfor %}
                </ul>
              </div>
              <hr>
              <div class="row-fluid tags">
                <div class="title-tags-content">
                  <img class="headerIcon" src="/static/img/comments.gif" alt="comments">
                  <h4>Tags</h4>
                </div>
                <ul class="tags">
                  {% for tag in tags %}
                  <li class="tag">
                    <a href="{% url 'dashboard' %}?filter=tag&tag={{ tag }}">#{{tag}}</a>
                  </li>
                  {% endfor %}
                </ul>
              </div>
              <hr>
              <div class="row-fluid related-comments">
                <div class="title-related-content">
                  <img class="headerIcon" src="/static/img/comments.gif" alt="comments">
                  <h4>Comments</h4>
                </div>
                {% render_comment_list for post %}
                {% render_comment_form for post %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    $("#id_comment").removeAttr("rows");
    $("#id_comment").removeAttr("cols");
  </script>
{% endblock %}

templates/ui/shuffle.html
{% extends "base.html" %}
{% load i18n %}
{% load thumbnail %}
{% block content %}
  <div id="container">
    <div class="row-fluid">
      <br>
    </div>
    <div id="posts" class="isotope row">
    <!-- Posts will go here ... -->
    </div>

    <script src="http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>
    <script src="{{STATIC_URL}}js/jquery.ba-hashchange.min.js"></script>
    <script src="{{STATIC_URL}}js/jquery.isotope.min.js"></script>
    <script src="{{STATIC_URL}}js/mql.js"></script>
    <script src="{{STATIC_URL}}js/oyf.js"></script>
    <script src="{{STATIC_URL}}js/script.js"></script>

    <script id="post" type="text/x-jquery-tmpl">
      <div id="postid-${id}" class="post item span4">
        <div class="well post-well">
          <div id="circle-menu">
            <!-- first expaning path menu -->                        
              <a class="centerbutton" href="javascript:void(0);" title="Share!">
                <span></span>
              </a>
              <ul class="circles">
                <li><a href="" title="Share this on facebook"><span class="facebook"></span></a></li>
                <li><a href="" title="Share this on twitter"><span class="twitter"></span></a></li>
              </ul>
            <!-- second expaning path menu -->
              <a class="centerbutton2" href="javascript:void(0);" title="Add...">
              <span></span>
              </a>
              <ul class="circles2">
                <li><a href="javascript:void(0);" title="Follow this user"><span class="follow_user"></span></a></li>
                <li><a href="javascript:void(0);" title=""><span class="follow_tag"></span></a></li>
              </ul>
          </div> <!-- div menu -->
          <a href="${permalink}" title="${name}">
            <img src="${home_picture}" title="${name}">
            <!--<div class="info">
              <span class="badge">${score}</span>
            </div>-->
            <div class="post-title">
              <h3><span>${title}</span></h3>
            </div>
          </a>
        </div>
      </div>
    </script>
  </div>
{% endblock %}